// locationData.js

export const statesByCountry = {
  India: ["Delhi", "Maharashtra", "Karnataka", "Tamil Nadu", "West Bengal"],
  "United States": ["New York", "California", "Texas", "Florida", "Illinois"],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  Canada: ["Ontario", "British Columbia", "Quebec", "Alberta"],
  Australia: ["New South Wales", "Victoria", "Queensland"],
  Germany: ["Berlin", "Bavaria", "Hesse"],
  France: ["Île-de-France", "Provence-Alpes-Côte d'Azur"],
  China: ["Beijing", "Shanghai"],
  Japan: ["Tokyo", "Osaka"],
  Brazil: ["São_Paulo", "Rio_de_Janeiro"],
};

export const citiesByState = {
  Delhi: ["Delhi City", "New Delhi", "Dwarka", "Janakpuri", "Vasant Kunj"],
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
  Karnataka: ["Bangalore", "Mysore", "Mangalore", "Hubli", "Belgaum"],
  "New York": ["New York City", "Buffalo", "Rochester", "Syracuse", "Albany"],
  California: [
    "Los Angeles",
    "San Francisco",
    "San Diego",
    "Sacramento",
    "San Jose",
  ],
  Texas: ["Houston", "Austin", "Dallas", "San Antonio", "Fort Worth"],
  Florida: ["Miami", "Orlando", "Tampa", "Jacksonville", "Tallahassee"],
  Illinois: ["Chicago", "Aurora", "Naperville", "Rockford", "Peoria"],
  England: ["London", "Birmingham", "Manchester", "Liverpool", "Leeds"],
  Scotland: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness"],
  Wales: ["Cardiff", "Swansea", "Newport", "Wrexham", "Bangor"],
  NorthernIreland: [
    "Belfast",
    "Derry",
    "Lisburn",
    "Newtownabbey",
    "Carrickfergus",
  ],
  Ontario: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton"],
  "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby", "Kelowna"],
  Quebec: ["Montreal", "Quebec City", "Laval", "Gatineau", "Sherbrooke"],
  Alberta: ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Medicine Hat"],
  "New South Wales": [
    "Sydney",
    "Newcastle",
    "Wollongong",
    "Central Coast",
    "Coffs Harbour",
  ],
  Victoria: ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton"],
  Queensland: ["Brisbane", "Gold Coast", "Cairns", "Townsville", "Mackay"],
  Berlin: [
    "Berlin",
    "Potsdam",
    "Cottbus",
    "Brandenburg an der Havel",
    "Frankfurt (Oder)",
  ],
  Bavaria: ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Würzburg"],
  Hesse: ["Frankfurt", "Wiesbaden", "Darmstadt", "Kassel", "Marburg"],
  "Île-de-France": [
    "Paris",
    "Versailles",
    "Boulogne-Billancourt",
    "Argenteuil",
    "Saint-Denis",
  ],
  "Provence-Alpes-Côte d'Azur": [
    "Marseille",
    "Nice",
    "Toulon",
    "Aix-en-Provence",
    "Avignon",
  ],
  Beijing: ["Beijing", "Tianjin", "Shijiazhuang", "Baoding", "Tangshan"],
  Shanghai: ["Shanghai", "Suzhou", "Hangzhou", "Nanjing", "Wuxi"],
  Tokyo: ["Tokyo", "Yokohama", "Kawasaki", "Saitama", "Chiba"],
  Osaka: ["Osaka", "Kobe", "Kyoto", "Nara", "Hiroshima"],
  São_Paulo: ["São_Paulo", "Campinas", "Santos", "Sorocaba", "Ribeirão Preto"],
  Rio_de_Janeiro: [
    "Rio_de_Janeiro",
    "Niterói",
    "São Gonçalo",
    "Duque de Caxias",
    "Nova Iguaçu",
  ],
};
